"""Add type field to pet

Revision ID: 0490e1fe5ba5
Revises: d157b256785a
Create Date: 2026-02-08 18:40:56.744192

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0490e1fe5ba5'
down_revision = 'd157b256785a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'type')
    # ### end Alembic commands ###
