"""add sender_type to chatmessage

Revision ID: 6aff899b7a1a
Revises: 0490e1fe5ba5
Create Date: 2026-02-21 14:56:15.899538

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6aff899b7a1a'
down_revision = '0490e1fe5ba5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('fact_type', sa.Enum('Relationship', 'Like', 'Dislike', 'Location', 'HistoricalEvent', name='facttype'), nullable=False),
    sa.Column('fact_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fact_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fact_verb', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fact_predicate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fact_source_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_type', sa.Enum('USER', 'PET', name='sendertype'), nullable=False))
        batch_op.create_foreign_key('fk_chatmessage_conversation_id', 'conversation', ['conversation_id'], ['id'])
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_id')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_conversation_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_conversation_pet_id', 'pet', ['pet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversation_pet_id', 'conversation', type_='foreignkey')
    op.drop_constraint('fk_conversation_user_id', 'conversation', type_='foreignkey')
    op.add_column('chatmessage', sa.Column('sender_id', sa.VARCHAR(), nullable=False))
    op.add_column('chatmessage', sa.Column('receiver_id', sa.VARCHAR(), nullable=False))
    op.drop_constraint('fk_chatmessage_conversation_id', 'chatmessage', type_='foreignkey')
    op.drop_column('chatmessage', 'sender_type')
    op.drop_table('fact')
    # ### end Alembic commands ###
